name = "dynamic-ar-viewer"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
# OpenNext output directory
pages_build_output_dir = ".open-next/assets" 

[[r2_buckets]]
binding = "MODELS_BUCKET"
bucket_name = "armodelviewer"
