name = "dynamic-ar-viewer"
main = ".open-next/worker.js"
compatibility_date = "2026-02-04"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[r2_buckets]]
binding = "MODELS_BUCKET"
bucket_name = "armodelviewer"
